In [10]:
import pandas as pd

In [13]:
#Demonstração de um pedaço do pipeline realizado até agora nas aulas:

#pré-processamento
import pandas as pd

dados=pd.read_csv('weight_change_dataset.csv')
dados=dados.dropna()
display(dados.describe())

#processamento
peso_inicial=dados.groupby('Current Weight (lbs)').sum()


#exibição/apresentação
peso_inicial

,Participant ID,Age,Current Weight (lbs),BMR (Calories),Daily Calories Consumed,Daily Caloric Surplus/Deficit,Weight Change (lbs),Duration (weeks),Stress Level,Final Weight (lbs)
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,37.910000,171.533000,2518.206000,3518.292000,1000.091000,-2.779817,6.920000,4.810000,168.750000
std,29.011492,12.219454,30.333856,364.431221,513.313097,371.560827,7.443719,3.515277,2.576879,30.588004
min,1.000000,18.000000,100.000000,1566.500000,2030.900000,82.500000,-35.678115,1.000000,1.000000,98.200000
25%,25.750000,26.750000,153.650000,2255.050000,3233.300000,766.950000,-5.012312,4.000000,2.750000,149.550000
50%,50.500000,38.000000,172.150000,2519.500000,3636.050000,1013.100000,0.100000,7.000000,5.000000,169.800000
75%,75.250000,46.250000,192.475000,2805.975000,4000.000000,1253.325000,1.850000,10.000000,7.000000,188.300000
max,100.000000,59.000000,238.200000,3390.800000,4000.000000,1922.500000,5.000000,12.000000,9.000000,232.500000

C:\Users\60134552024.1\AppData\Local\Temp\ipykernel_13120\3892788731.py:11: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  peso_inicial=dados.groupby('Current Weight (lbs)').sum()

,Participant ID,Age,BMR (Calories),Daily Calories Consumed,Daily Caloric Surplus/Deficit,Weight Change (lbs),Duration (weeks),Stress Level,Final Weight (lbs)
Current Weight (lbs),,,,,,,,,
100.0,136,95,5326.8,7265.8,1939.1,-0.752411,11,14,299.2
107.3,7,36,1991.3,2933.4,942.1,-2.437307,2,5,104.9
113.4,80,32,1825.5,2987.7,1162.2,3.600000,12,1,117.0
114.5,67,32,1836.6,2724.7,888.2,-5.659247,4,5,108.8
116.5,97,56,1736.5,2756.5,1020.0,-8.923090,12,9,107.6
...,...,...,...,...,...,...,...,...,...
226.2,49,52,3100.4,4000.0,899.6,-1.620925,1,8,224.6
228.0,35,38,2941.7,4000.0,1058.3,0.900000,3,1,228.9
228.4,1,56,3102.3,3916.0,813.7,0.200000,1,6,228.6
234.8,23,50,3196.4,4000.0,803.6,-2.623361,4,2,232.2
238.2,81,18,3390.8,4000.0,609.2,-5.718496,10,3,232.5

In [11]:
pip install polars

Collecting polars
  Downloading polars-1.19.0-cp39-abi3-win_amd64.whl (32.8 MB)
     ---------------------------------------- 32.8/32.8 MB 8.7 MB/s eta 0:00:00
Installing collected packages: polars
Successfully installed polars-1.19.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 24.3.1 is available.
You should consider upgrading via the 'c:\Python310\python.exe -m pip install --upgrade pip' command.

In [23]:
#IMPORTANTE: utilize os dados de 2 meses para evitar a sobrecarga do programa!

import pandas as pd
import time

arquivo1=pd.read_csv("202410_NovoBolsaFamilia.csv", sep=";", encoding="latin-1") #caminhos dos arquivos
arquivo2=pd.read_csv("202411_NovoBolsaFamilia.csv", sep=";", encoding="latin-1")

inicio_tempo=time.time() #marcação do tempo de processamento
df_pandas=pd.concat([arquivo1,arquivo2])

display(df_pandas.head())

print("Tempo de execução com Pandas:", time.time() - inicio_tempo, "segundos")

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
0,202410,202310,CE,1441,JAGUARUANA,***.795.893-**,1.606232e+10,FRANCISCA CALCELENA DA SILVA,"650,00"
1,202410,202310,CE,1441,JAGUARUANA,***.210.363-**,1.289352e+10,PAULO SERGIO DA SILVA,"600,00"
2,202410,202310,MG,4575,GUIDOVAL,***.403.916-**,2.091714e+10,ANA PAULA MORAIS ROMUALDO,"750,00"
3,202410,202310,PA,493,MOJU,***.144.702-**,1.601995e+10,DINALVA DO CARMO NEVES,"300,00"
4,202410,202310,PE,2303,AFRANIO,***.838.234-**,1.601252e+10,HELSON TELLES MATA,"750,00"

Tempo de execução com Pandas: 35.48086714744568 segundos